w/TetrisEnv:
  n_timesteps: !!float 1e6
  policy: 'MultiInputPolicy'
  batch_size: 64
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.9
  n_epochs: 20
  ent_coef: 0.0
  max_grad_norm: 0.5
  vf_coef: 0.5
  learning_rate: !!float 3e-5
  clip_range: lin_0.4
